import type { QuizAnswers } from "./types";

export interface DemoPerson {
  id: string;
  name: string;
  age: number;
  university: string;
  city: string;
  bio: string;
  budget: string;
  move_in_date: string;
  answers: Omit<QuizAnswers, "user_id" | "updated_at">;
}

export const DEMO_PEOPLE: DemoPerson[] = [
  {
    id: "demo-1",
    name: "Priya Patel",
    age: 21,
    university: "University of Warwick",
    city: "Coventry",
    bio: "Engineering student. Climbs three times a week. Cooks most nights and loves a shared dinner. Looking for someone who keeps things clean but isn't obsessive about it.",
    budget: "£500–£700",
    move_in_date: "2026-09-01",
    answers: { sleep_schedule: 3, cleanliness: 4, noise_level: 3, guests_frequency: 2, study_location: 2, smoking: false, pets: false, cooking_frequency: 5, temperature_preference: 3, work_schedule: 3 },
  },
  {
    id: "demo-2",
    name: "Oliver Chen",
    age: 24,
    university: "Imperial College London",
    city: "London",
    bio: "Maths PhD. Honestly just want quiet evenings, board games on Sundays, and decent wifi. I work late but keep headphones on. Happy to share cooking duties.",
    budget: "£750–£1,100",
    move_in_date: "2026-08-15",
    answers: { sleep_schedule: 2, cleanliness: 4, noise_level: 2, guests_frequency: 1, study_location: 1, smoking: false, pets: false, cooking_frequency: 3, temperature_preference: 3, work_schedule: 2 },
  },
  {
    id: "demo-3",
    name: "Aisha Khan",
    age: 20,
    university: "University of Manchester",
    city: "Manchester",
    bio: "Pre-med. Gym at 6am, in bed by 11. Tidy without being intense about it. Tea over coffee, always. I'm vegetarian and love batch-cooking on Sundays.",
    budget: "£450–£650",
    move_in_date: "2026-09-01",
    answers: { sleep_schedule: 1, cleanliness: 5, noise_level: 2, guests_frequency: 1, study_location: 3, smoking: false, pets: false, cooking_frequency: 4, temperature_preference: 4, work_schedule: 1 },
  },
  {
    id: "demo-4",
    name: "Mateo Garcia",
    age: 22,
    university: "University of Edinburgh",
    city: "Edinburgh",
    bio: "Architecture student — sometimes home, sometimes studio until 2am. Love a kitchen disco and a clean fridge. My cat Pepita is non-negotiable.",
    budget: "£500–£750",
    move_in_date: "2026-07-01",
    answers: { sleep_schedule: 4, cleanliness: 3, noise_level: 4, guests_frequency: 3, study_location: 4, smoking: false, pets: true, cooking_frequency: 3, temperature_preference: 4, work_schedule: 5 },
  },
  {
    id: "demo-5",
    name: "Hannah O'Brien",
    age: 19,
    university: "University of Leeds",
    city: "Leeds",
    bio: "Politics, first year. Big on pub quizzes and debating. Will absolutely respect the chore rota. Early riser who needs coffee before speaking to anyone.",
    budget: "£400–£600",
    move_in_date: "2026-09-15",
    answers: { sleep_schedule: 4, cleanliness: 4, noise_level: 4, guests_frequency: 4, study_location: 4, smoking: false, pets: false, cooking_frequency: 2, temperature_preference: 3, work_schedule: 4 },
  },
  {
    id: "demo-6",
    name: "Ravi Sharma",
    age: 23,
    university: "University of Bristol",
    city: "Bristol",
    bio: "CS masters. Night owl coder, daytime climber. I keep my room messy but common areas clean. Big on homemade curry. Need a flatmate who gets it.",
    budget: "£550–£800",
    move_in_date: "2026-09-01",
    answers: { sleep_schedule: 5, cleanliness: 2, noise_level: 3, guests_frequency: 2, study_location: 1, smoking: false, pets: false, cooking_frequency: 5, temperature_preference: 2, work_schedule: 5 },
  },
  {
    id: "demo-7",
    name: "Sophie Williams",
    age: 20,
    university: "University of Birmingham",
    city: "Birmingham",
    bio: "English Lit. Basically live in coffee shops. Quiet at home, social outside. I run a small Etsy shop so there might be craft supplies around.",
    budget: "£400–£550",
    move_in_date: "2026-08-01",
    answers: { sleep_schedule: 3, cleanliness: 3, noise_level: 2, guests_frequency: 2, study_location: 5, smoking: false, pets: false, cooking_frequency: 2, temperature_preference: 3, work_schedule: 3 },
  },
  {
    id: "demo-8",
    name: "Jake Thompson",
    age: 21,
    university: "University of Glasgow",
    city: "Glasgow",
    bio: "Sports science. Train every day, eat a lot, sleep early. Looking for someone who won't judge protein shakes at 7am. Clean kitchen is a must.",
    budget: "£400–£600",
    move_in_date: "2026-09-01",
    answers: { sleep_schedule: 1, cleanliness: 5, noise_level: 3, guests_frequency: 3, study_location: 3, smoking: false, pets: false, cooking_frequency: 5, temperature_preference: 3, work_schedule: 1 },
  },
  {
    id: "demo-9",
    name: "Fatima Al-Rashid",
    age: 22,
    university: "King's College London",
    city: "London",
    bio: "Law. Library 9–5, home for dinner, study again until midnight. I'm tidy, quiet, and make amazing baklava. Prefer a non-smoking flat.",
    budget: "£700–£1,000",
    move_in_date: "2026-08-15",
    answers: { sleep_schedule: 2, cleanliness: 5, noise_level: 1, guests_frequency: 1, study_location: 5, smoking: false, pets: false, cooking_frequency: 4, temperature_preference: 4, work_schedule: 2 },
  },
  {
    id: "demo-10",
    name: "Liam Murphy",
    age: 25,
    university: "University of Nottingham",
    city: "Nottingham",
    bio: "PhD in History. Total night owl — writing my thesis at 3am is normal. Messy desk, clean kitchen. I smoke outside only. Dog-friendly please!",
    budget: "£450–£650",
    move_in_date: "2026-07-15",
    answers: { sleep_schedule: 5, cleanliness: 2, noise_level: 2, guests_frequency: 1, study_location: 1, smoking: true, pets: true, cooking_frequency: 3, temperature_preference: 2, work_schedule: 5 },
  },
  {
    id: "demo-11",
    name: "Emma Davis",
    age: 19,
    university: "University of Exeter",
    city: "Exeter",
    bio: "Marine biology. Surf before lectures, study at the beach. Very social — friends over 3–4 times a week. Life's too short for a quiet flat!",
    budget: "£400–£600",
    move_in_date: "2026-09-01",
    answers: { sleep_schedule: 4, cleanliness: 2, noise_level: 5, guests_frequency: 5, study_location: 4, smoking: false, pets: true, cooking_frequency: 1, temperature_preference: 2, work_schedule: 4 },
  },
  {
    id: "demo-12",
    name: "Noah Kim",
    age: 21,
    university: "University of Sheffield",
    city: "Sheffield",
    bio: "Music production. I have a home studio setup (headphones, don't worry). Night sessions, late mornings. Chill vibes, takeaway lover.",
    budget: "£350–£550",
    move_in_date: "2026-09-01",
    answers: { sleep_schedule: 5, cleanliness: 2, noise_level: 4, guests_frequency: 3, study_location: 1, smoking: true, pets: false, cooking_frequency: 1, temperature_preference: 3, work_schedule: 5 },
  },
  {
    id: "demo-13",
    name: "Charlotte Evans",
    age: 20,
    university: "University of Bath",
    city: "Bath",
    bio: "Chemical engineering. Balanced schedule — study hard, relax harder. I bake when stressed and my sourdough starter has a name. Clean freak, sorry not sorry.",
    budget: "£500–£700",
    move_in_date: "2026-08-01",
    answers: { sleep_schedule: 3, cleanliness: 5, noise_level: 3, guests_frequency: 2, study_location: 3, smoking: false, pets: false, cooking_frequency: 5, temperature_preference: 3, work_schedule: 3 },
  },
  {
    id: "demo-14",
    name: "Daniel Okafor",
    age: 23,
    university: "UCL",
    city: "London",
    bio: "Economics masters. I split time between the library and networking events. Social calendar is packed. If you're up for spontaneous dinners out, we'll get along.",
    budget: "£800–£1,200",
    move_in_date: "2026-09-15",
    answers: { sleep_schedule: 4, cleanliness: 3, noise_level: 5, guests_frequency: 5, study_location: 5, smoking: false, pets: false, cooking_frequency: 1, temperature_preference: 4, work_schedule: 4 },
  },
  {
    id: "demo-15",
    name: "Isla MacGregor",
    age: 18,
    university: "University of St Andrews",
    city: "St Andrews",
    bio: "First year, History & Politics. Still figuring it out honestly. Quiet, read a lot, enjoy long walks. Would like someone patient and kind.",
    budget: "£400–£600",
    move_in_date: "2026-09-01",
    answers: { sleep_schedule: 2, cleanliness: 4, noise_level: 1, guests_frequency: 1, study_location: 2, smoking: false, pets: false, cooking_frequency: 3, temperature_preference: 4, work_schedule: 2 },
  },
  {
    id: "demo-16",
    name: "Marcus Johnson",
    age: 22,
    university: "University of Warwick",
    city: "Coventry",
    bio: "Business & Management. Gym bro meets spreadsheet nerd. I meal prep every Sunday and have a cleaning schedule on the fridge. Yes, it's colour-coded.",
    budget: "£500–£700",
    move_in_date: "2026-09-01",
    answers: { sleep_schedule: 1, cleanliness: 5, noise_level: 3, guests_frequency: 2, study_location: 4, smoking: false, pets: false, cooking_frequency: 5, temperature_preference: 3, work_schedule: 1 },
  },
  {
    id: "demo-17",
    name: "Zara Hussain",
    age: 21,
    university: "University of Liverpool",
    city: "Liverpool",
    bio: "Nursing student. Shift patterns are chaos — sometimes home at 7am, sometimes leaving at 7am. I'm quiet, tidy, and genuinely just need sleep.",
    budget: "£350–£500",
    move_in_date: "2026-08-01",
    answers: { sleep_schedule: 3, cleanliness: 4, noise_level: 1, guests_frequency: 1, study_location: 3, smoking: false, pets: false, cooking_frequency: 3, temperature_preference: 4, work_schedule: 3 },
  },
  {
    id: "demo-18",
    name: "Tom Brennan",
    age: 24,
    university: "University of Cambridge",
    city: "Cambridge",
    bio: "Finishing up a PhD in physics. Social smoker. I have a rescue greyhound who sleeps 20 hours a day. Messy but functional. Late-night tea drinker.",
    budget: "£600–£900",
    move_in_date: "2026-07-01",
    answers: { sleep_schedule: 5, cleanliness: 1, noise_level: 3, guests_frequency: 3, study_location: 1, smoking: true, pets: true, cooking_frequency: 2, temperature_preference: 2, work_schedule: 5 },
  },
];
